name: room_ai
description: Transform your space with AI.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.5
  image_picker: ^0.8.7
  uuid: ^3.0.7
  supabase_flutter: ^1.10.4
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.11
  path_provider: ^2.0.15
  share_plus: ^7.0.2
  shared_preferences: ^2.2.0
  image: ^4.0.17
  device_info_plus: ^8.2.2
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

dependency_overrides:
  win32: 2.7.0  # Use a specific older version without UnmodifiableUint8ListView
  collection: 1.16.0  # Pin collection to a compatible version
  http_parser: 4.0.2  # Use an older version that's compatible with your dependencies