/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/building-type`; params?: Router.UnknownInputParams; } | { pathname: `/color-palette`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/prompt-input`; params?: Router.UnknownInputParams; } | { pathname: `/results`; params?: Router.UnknownInputParams; } | { pathname: `/room-selection`; params?: Router.UnknownInputParams; } | { pathname: `/style-selection`; params?: Router.UnknownInputParams; } | { pathname: `/saved-designs`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/context/AppContext`; params?: Router.UnknownInputParams; } | { pathname: `/services/aiService`; params?: Router.UnknownInputParams; } | { pathname: `/services/supabaseService`; params?: Router.UnknownInputParams; } | { pathname: `/utils/constants`; params?: Router.UnknownInputParams; } | { pathname: `/utils/urlUtils`; params?: Router.UnknownInputParams; } | { pathname: `/utils/theme`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/building-type`; params?: Router.UnknownOutputParams; } | { pathname: `/color-palette`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/prompt-input`; params?: Router.UnknownOutputParams; } | { pathname: `/results`; params?: Router.UnknownOutputParams; } | { pathname: `/room-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/style-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/saved-designs`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/context/AppContext`; params?: Router.UnknownOutputParams; } | { pathname: `/services/aiService`; params?: Router.UnknownOutputParams; } | { pathname: `/services/supabaseService`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/constants`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/urlUtils`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/theme`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/building-type${`?${string}` | `#${string}` | ''}` | `/color-palette${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/prompt-input${`?${string}` | `#${string}` | ''}` | `/results${`?${string}` | `#${string}` | ''}` | `/room-selection${`?${string}` | `#${string}` | ''}` | `/style-selection${`?${string}` | `#${string}` | ''}` | `/saved-designs${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/context/AppContext${`?${string}` | `#${string}` | ''}` | `/services/aiService${`?${string}` | `#${string}` | ''}` | `/services/supabaseService${`?${string}` | `#${string}` | ''}` | `/utils/constants${`?${string}` | `#${string}` | ''}` | `/utils/urlUtils${`?${string}` | `#${string}` | ''}` | `/utils/theme${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/building-type`; params?: Router.UnknownInputParams; } | { pathname: `/color-palette`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/prompt-input`; params?: Router.UnknownInputParams; } | { pathname: `/results`; params?: Router.UnknownInputParams; } | { pathname: `/room-selection`; params?: Router.UnknownInputParams; } | { pathname: `/style-selection`; params?: Router.UnknownInputParams; } | { pathname: `/saved-designs`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/context/AppContext`; params?: Router.UnknownInputParams; } | { pathname: `/services/aiService`; params?: Router.UnknownInputParams; } | { pathname: `/services/supabaseService`; params?: Router.UnknownInputParams; } | { pathname: `/utils/constants`; params?: Router.UnknownInputParams; } | { pathname: `/utils/urlUtils`; params?: Router.UnknownInputParams; } | { pathname: `/utils/theme`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
